=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/apps/quicksec.dtd
<!--                                                                    -->
<!-- quicksec.dtd                                                       -->
<!--                                                                    -->
<!-- @copyright                                                         -->
<!-- Copyright (c) 2002 - 2016, INSIDE Secure Oy.  All rights reserved. -->
<!--                                                                    -->
<!-- Document type description for QuickSec XML policy files.           -->
<!--                                                                    -->
<!--                                                                    -->

<!-- Built-in entities:                                                 -->
<!--                                                                    -->
<!--   quicksec:hostname                                                -->
<!--   quicksec:version                                                 -->
<!--   quicksec:ifname(IFINDEX[,TYPE])                                  -->
<!--     where:                                                         -->
<!--       IFINDEX  is the interface number                             -->
<!--       TYPE     is `any', `loopback' or `physical'                  -->
<!--                                                                    -->


<!-- Tunable parameters used in the policy. -->

<!ENTITY vpn-a-transform    'esp 3des sha1'>

<!ENTITY vpn-a-group        '2'>

<!ENTITY vpn-a-ike-life     '86400'>

<!ENTITY vpn-a-ipsec-life   '28800'>

<!ENTITY vpn-b-transform    'esp aes xcbc-aes'>

<!ENTITY vpn-b-group        '14'>

<!ENTITY vpn-b-ike-life     '86400'>

<!ENTITY vpn-b-ipsec-life   '28800'>

<!-- Default lifetime type. -->
<!ENTITY % default-life-type    '"kbytes"'>

<!-- Default rule type. -->
<!ENTITY % default-rule-type    '"pass"'>

<!-- Policy elements and their attributes. -->

<!-- The top-level element. -->
<!ELEMENT quicksec  (params?,policy+)>

<!-- Parameter element. -->
<!ELEMENT params (audit?
                  ,http-interface?
                  ,dns?
                  ,xauth-tester?
                  ,mobike?
                  ,(address-pool
                    |externalkey
                    |ldap
                    |client-auth
                    |group
                    |auth-domain)*
                  ,xauth-method?
                  ,radius-accounting?
                  ,ike-redirect?
                  ,ike-fragmentation?)>

<!-- IKEv2 Fragmentation -->
<!ELEMENT ike-fragmentation     EMPTY>
<!ATTLIST ike-fragmentation
          status                (disabled|enabled)  "enabled"
          fragment-size         CDATA               "1280">

<!-- IKE Redirect -->
<!--  phase: ike-init -->
<!ELEMENT ike-redirect (redirect-address*)>
<!ATTLIST ike-redirect
          phase     CDATA    #IMPLIED>


<!-- cookie-required : with ikev2 always do cookie exchange -->
<!-- certificate-provider : enable hash-and-url certificate provider -->
<!-- certificate-bundles : send hash-and-url certificates as bundles -->
<!ATTLIST params
          flags                         NMTOKENS    #IMPLIED
          debug                         CDATA       #IMPLIED
          certificate-provider-port     CDATA       "7369">

<!-- Audit Configuration. -->
<!ELEMENT audit (module*)>
<!ATTLIST audit
          snap-length   CDATA     "0">

<!ELEMENT module    EMPTY>
<!ATTLIST module
          log-to    CDATA         "syslog"
          format    NMTOKENS      "default">
<!-- all ike pm -->
<!ATTLIST module
          subsystem     NMTOKENS      "all">

<!-- HTTP statistics interface. -->
<!ELEMENT http-interface    EMPTY>
<!ATTLIST http-interface
          address       CDATA       #IMPLIED
          port          CDATA       "7368"
          frames        (yes|no)    "no"
          refresh       CDATA       "0">

<!-- DNS name resolver utilization. -->
<!ELEMENT dns                   EMPTY>

<!-- XAUTH tester. -->
<!ELEMENT xauth-tester  ANY>

<!-- Mobike. rrc-policy: before-sa-update after-sa-update no-rrc -->
<!ELEMENT mobike                EMPTY>
<!ATTLIST mobike
          rrc-policy            CDATA           #IMPLIED>

<!-- Address pool for allocating IP addresses for remote access -->
<!-- clients. -->
<!ELEMENT address-pool  (subnet*,address*,ipv6-prefix?)>
<!ATTLIST address-pool
          name      ID      #IMPLIED
          own-ip    CDATA   #IMPLIED
          dns       CDATA   #IMPLIED
          wins      CDATA   #IMPLIED
          dhcp      CDATA   #IMPLIED
          flags     CDATA   #IMPLIED>

<!-- Additional sub-networks, protected by the gateway -->
<!-- (SUBNET/MASKLEN). -->
<!ELEMENT subnet    (#PCDATA)>

<!-- IPv6 prefix, used when clients specify the low-order address bits -->
<!ELEMENT ipv6-prefix   (#PCDATA)>

<!-- An IP address specification.  Possible formats are:        -->
<!--   IPADDR       a single IP address                 -->
<!--   IPADDR-IPADDR    an IP address range                 -->
<!--   IPADDR/MASKLEN   all addresses of the subnet.  If the netmask    -->
<!--            attribute is unspecified, use the netmask   -->
<!--            MASKLEN.                    -->
<!ELEMENT address   (#PCDATA)>
<!ATTLIST address
          netmask   CDATA   #IMPLIED>

<!-- Externalkey provider. -->
<!ELEMENT externalkey   EMPTY>
<!ATTLIST externalkey
      type      CDATA       #REQUIRED
      init-info CDATA       #IMPLIED>

<!-- trust-cas -->
<!ATTLIST externalkey
      flags     NMTOKENS    #IMPLIED>

<!-- An LDAP server. -->
<!ELEMENT ldap EMPTY>
<!ATTLIST ldap
      server    CDATA   #REQUIRED
      port      CDATA   "389">

<!-- Remote access client authentication. -->
<!ELEMENT client-auth   EMPTY>
<!ATTLIST client-auth
          type      (xauth|eap)            #IMPLIED
          gateway   CDATA                   #IMPLIED
          order         (1|2)                       #IMPLIED
          user-name CDATA                   #REQUIRED
          password  CDATA                   #REQUIRED>

<!-- Authentication domains -->
<!ELEMENT auth-domain ((remote-secret
                       |certificate
                       |ca
                       |crl
                       |eap
                       |radius-client|radius
                       |password)*)>
<!ATTLIST auth-domain
          name          CDATA    #IMPLIED>

<!-- User-name - password based authentication at the remote access -->
<!-- gateway. -->
<!ELEMENT password  EMPTY>
<!ATTLIST password
          user-name             CDATA               #REQUIRED
          password              CDATA               #REQUIRED
          user-name-encoding    (binary|hex)        "binary"
          password-encoding     (binary|hex)        "binary">

<!-- Additional manually configured certificates and CRLs. -->

<!ELEMENT certificate   (#PCDATA)>
<!ATTLIST certificate
          file      CDATA   #IMPLIED>

<!ELEMENT crl       (#PCDATA)>
<!ATTLIST crl
          file      CDATA   #IMPLIED>

<!-- A pre-shared key for a remote IKE peer. -->
<!ELEMENT remote-secret     (#PCDATA)>
<!ATTLIST remote-secret
          id-type     (dn|ip|fqdn|email|key-id|idlist)    #IMPLIED
          id          CDATA                               #IMPLIED
          id-encoding (binary|hex)                        "binary"
          encoding    (binary|hex)                        "binary">

<!-- EAP configuration -->
<!ELEMENT eap           EMPTY>
<!ATTLIST eap
          type          (md5-challenge
                         |sim
                         |aka
                         |srp
                         |tls
                         |aka-dash
                         |mschapv2)                             #IMPLIED
          radius-url    CDATA                                   #IMPLIED
          preference    CDATA                                   #IMPLIED>


<!-- RADIUS client information. -->
<!ELEMENT radius-client     EMPTY>
<!ATTLIST radius-client
          address               CDATA   #REQUIRED
          port                  CDATA   #IMPLIED
          nas-ip-address        CDATA   #IMPLIED
          nas-identifier        CDATA   #IMPLIED
          max-retransmit-timer  CDATA   #IMPLIED
          max-retransmissions   CDATA   #IMPLIED>

<!-- RADIUS server information. -->
<!ELEMENT radius    EMPTY>
<!ATTLIST radius
          server    CDATA   #REQUIRED
          port      CDATA   "1812"
          acct-port CDATA   "1813"
          secret    CDATA   #REQUIRED>

<!-- Access control group. -->
<!ELEMENT group (constraint+)>
<!ATTLIST group
          name  CDATA   #REQUIRED>

<!-- Constraint for members of an access control group. -->
<!ELEMENT constraint    EMPTY>
<!ATTLIST constraint
          type      (xauth
                     |eap
                     |key-subject
                     |eap-subject
                     |cert-subject
                     |cert-issuer
                     |ca-subject)           #REQUIRED>
<!-- Type           Field   Pattern             -->
<!-- ================================================================== -->
<!-- xauth          radius  AVP=PATTERN         -->
<!-- For `{cert,ca}-subject'    dn  PATTERN for subjectName     -->
<!-- and `cert-issuer'      ip  PATTERN for IP subjectAltName   -->
<!-- types          fqdn    PATTERN for fqdn subjectAltName -->
<!--                email   PATTERN for emailsubjectAltName -->
<!-- key-subject may use ip, fqdn, email and key-id types -->


<!-- eap   auth-method  PATTERN sim|aka|tls|md5-challenge|aka-dash      -->
<!-- eap-subject Field may be ip, fqdn, email or key-id                 -->
<!-- eap-subject Pattern  should match the EAP identity                 -->

<!ATTLIST constraint
          field     CDATA               #IMPLIED
          pattern   CDATA               #IMPLIED>


<!-- Type of External authentication method used for authentication. -->
<!-- The method type and flag values should have the following values-->
<!--  Type                              FLAG                         -->
<!-- =============================================================== -->
<!-- generic                           simple                        -->
<!--                                   securid                       -->
<!-- radius-chap                                                     -->
<!-- otp                                                             -->
<!-- s-key                                                           -->
<!ELEMENT xauth-method EMPTY>
<!ATTLIST xauth-method
          type     CDATA #IMPLIED
          flag     CDATA #IMPLIED>


<!ELEMENT radius-accounting (radius-client, radius+)>
<!ATTLIST radius-accounting>

<!-- Policy element. -->
<!ELEMENT policy ((ldap
                   |password
                   |ike-defaults
                   |certificate
                   |crl
                   |group)*
                  ,(tunnel|rule)+)>
<!ATTLIST policy
          id            ID      #IMPLIED
          precedence    CDATA   #IMPLIED
          size          CDATA   #IMPLIED
          refresh       CDATA   "0">

<!-- Default IKE parameters and algorithms. -->
<!ELEMENT ike-defaults  EMPTY>
<!-- cipher1 cipher2 null des 3des aes aes-ctr aes-gcm aes-gcm-64 -->
<!-- aes-gcm-96 aes-ccm aes-ccm-64 aes-ccm-96 -->
<!-- mac1 mac2 md5 sha1 -->
<!ATTLIST ike-defaults
          algorithms    NMTOKENS    #IMPLIED>

<!-- A tunnel specification. -->
<!ELEMENT tunnel    ((ike-versions
             |ike-groups
             |pfs-groups
             |life
             |certificate
             |identity
             |authentication
             |dpd-timeout
             |ike-algorithms
             |ike-window-size
             |local-ip
             |local-interface
             |local-port
             |ipsec-idle-timeout
             |peer
             |algorithm-properties
             |tunnel-address-pool
             |redirect-address
             |ike-fragmentation)*)>

<!ATTLIST tunnel
          name              ID      #REQUIRED
          app-id            CDATA   #IMPLIED
          ike-life          CDATA   #IMPLIED
          routing-instance  CDATA   #IMPLIED>

<!-- cipher1 cipher2 null des 3des aes aes-ctr aes-gcm aes-gcm-64 -->
<!-- aes-gcm-96 aes-ccm aes-ccm-64 aes-ccm-96 -->
<!-- mac1 mac2 md5 sha1 sha2 xcbc-aes gmac-aes -->
<!-- esp -->
<!-- Default transform is "esp aes 3des sha1 md5" -->

<!ATTLIST tunnel
          transform NMTOKENS    #IMPLIED>

<!-- perhost perport dont-initiate dhcp -->
<!-- omit-trigger-packet aggressive-mode allow-dhcp -->
<!-- allow-cfgmode require-cfgmode auto -->
<!-- tunnel transport disable-anti-replay eap-request-id -->
<!-- eap-only-authentication start-with-natt dont-initiate-natt -->
<!-- disable-natt no-nats-allowed xauth-methods mobike -->
<!-- long-seq short-seq no-cert-chains -->
<!ATTLIST tunnel
          flags     NMTOKENS    #IMPLIED>

<!ELEMENT redirect-address  (#PCDATA)>

<!-- An IKE peer, IP address or Domain name -->
<!ELEMENT peer  (#PCDATA)>

<!-- Local IP address to be used with a tunnel. -->
<!ELEMENT local-ip  (#PCDATA)>
<!ATTLIST local-ip
          precedence    NMTOKENS    #IMPLIED>

<!-- Local interface to be used with a tunnel. -->
<!ELEMENT local-interface (#PCDATA)>
<!ATTLIST local-interface
          precedence    NMTOKENS    #IMPLIED>

<!-- Local IKE port to be used with the tunnel. -->
<!ELEMENT local-port    (#PCDATA)>

<!-- DPD timeout. -->
<!ELEMENT dpd-timeout    (#PCDATA)>

<!-- Allowed Diffie-Hellman groups for IKE. -->
<!ELEMENT ike-groups    (#PCDATA)>
<!-- system-preferences -->
<!ATTLIST ike-groups
          flags     NMTOKENS    #IMPLIED>

<!-- Allowed IKE versions, currently support 1 and 2.   -->
<!-- If both given, initiator starts with version 2.    -->
<!-- If only 2 given start with version 2, no fallback. -->
<!-- If only 1 given, start with version 1, and on responder set USE_V1. -->
<!ELEMENT ike-versions (#PCDATA)>

<!-- Idle timeout be used with the tunnel. -->
<!ELEMENT ipsec-idle-timeout    (#PCDATA)>

<!-- Perfect forward secrecy. -->
<!ELEMENT pfs-groups    (#PCDATA)>
<!-- system-preferences -->
<!ATTLIST pfs-groups
          flags     NMTOKENS    #IMPLIED>

<!-- A required access control group. -->
<!ELEMENT access-group  (#PCDATA)>

<!-- SA lifetime. -->
<!ELEMENT life  (#PCDATA)>
<!ATTLIST life
          type  (kbytes|seconds)    %default-life-type;>

<!-- Trusted CA. -->
<!ELEMENT ca    (#PCDATA)>
<!ATTLIST ca
          file  CDATA       #IMPLIED>
<!-- no-crl -->
<!ATTLIST ca
          flags NMTOKENS    #IMPLIED>

<!-- An IKE identity. -->
<!ELEMENT identity (local-secret*)>

<!-- A pre-shared key for tunnel authenticaton. -->
<!ELEMENT local-secret                        (#PCDATA)>
<!ATTLIST local-secret
          encoding      (binary|hex)           "binary"
          flags         NMTOKENS               #IMPLIED>


<!ATTLIST identity
          id-type      (dn|ip|fqdn|email|key-id|idlist)    #IMPLIED
          id           CDATA                               #IMPLIED
          id-encoding  (binary|hex)                        "binary"
          type         (local|remote)                      "local"
          order        (1|2)                               "1">

<!-- enforce-identity -->
<!ATTLIST identity
          flags NMTOKENS    #IMPLIED>

<!-- Tunnel authentication -->
<!ELEMENT authentication    EMPTY>
<!ATTLIST authentication
          auth-domain-name      CDATA           #IMPLIED
          order                 (1|2)           "1">

<!-- Algorithm properties. -->
<!ELEMENT algorithm-properties  EMPTY>
<!-- cipher1 cipher2 aes aes-ctr aes-gcm aes-gcm-64 aes-gcm-96 gmac-aes -->
<!-- aes-ccm aes-ccm-64 aes-ccm-96 sha2 mac1 mac2 -->

<!ATTLIST algorithm-properties
          algorithm     NMTOKENS    #REQUIRED>

<!ATTLIST algorithm-properties
          min-key-size      CDATA           #REQUIRED
          max-key-size      CDATA           #REQUIRED
          default-key-size  CDATA           #REQUIRED
          scope             (ike|ipsec|all) "all">

<!-- Algorithms for IKE SAs. -->
<!-- cipher1 cipher2 des 3des aes aes-ctr mac1 mac2 md5 sha1 sha2 xcbc-aes -->
<!-- aes-gcm aes-gcm-64 aes-gcm-96 aes-ccm aes-ccm-64 aes-ccm-96 -->
<!ELEMENT ike-algorithms    (#PCDATA)>

<!ELEMENT ike-window-size   (#PCDATA)>

<!-- Configuring address pools to tunnels -->
<!ELEMENT tunnel-address-pool  EMPTY>
<!ATTLIST tunnel-address-pool
          name          IDREF                   #REQUIRED>

<!-- A policy rule. -->
<!ELEMENT rule     ((src|src-dns)?
                   ,(dst|dst-dns)?
                   ,access-group*)>

<!ATTLIST rule
          app-id                    ID                  #IMPLIED
          precedence                CDATA               #IMPLIED
          type                      (pass|reject|drop)  %default-rule-type;
          from-tunnel               IDREF               #IMPLIED
          to-tunnel                 IDREF               #IMPLIED
          routing-instance          CDATA               #IMPLIED>

<!-- connections -->
<!ATTLIST rule
          log       NMTOKENS        #IMPLIED>

<!-- rate-limit -->
<!ATTLIST rule
          flags     NMTOKENS        #IMPLIED>

<!-- Rule selectors. -->

<!ELEMENT src       (#PCDATA)>
<!ELEMENT dst       (#PCDATA)>
<!ELEMENT src-dns   (#PCDATA)>
<!ELEMENT dst-dns   (#PCDATA)>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hosta-ikev1-cfgmode-gw.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Remote access setup with IKEv1. -->
<!-- Related: hostb-ikev1-cfgmode-client.xml -->
<quicksec>
  <params>
    <!-- IRAS gives virtual IP address from range defined 
         in address element. Subnet element defines which subnet
         is accessible through the gateway. More than one subnet
         element can be defined. -->
    <address-pool>
      <subnet>192.168.200.0/24</subnet>
      <subnet>192.168.100.0/24</subnet>
      <address netmask="255.255.255.0">192.168.200.3-192.168.200.254</address>
    </address-pool> 

    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- shared secret and identity of remote IKE peer -->
      <remote-secret id-type="email" 
                     id="b@ipsec.com">foo</remote-secret>
    </auth-domain>
  </params>
  <policy>

      <tunnel name="remote-access" flags="allow-cfgmode
                                          aggressive-mode">
      <!-- local identity sent to the remote IKE peer -->
      <identity id-type="email" id="a@ipsec.com">
        <!-- local shared secret -->
        <local-secret>foo</local-secret>
      </identity>
      <ike-versions>1</ike-versions>
    </tunnel>

    <!-- Allow traffic from the remote access clients. -->
    <rule from-tunnel="remote-access"/>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>

  </policy>
</quicksec>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hosta-ike-redirect.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">

<!-- Client/Initiator configuration indicating support for IKE redirection -->

<quicksec>
  <params>
    <auth-domain>
      <remote-secret id-type="email" 
                     id="b@ipsec.com">foo</remote-secret>
    </auth-domain>

    <!-- Initiator supports/accepts redirection. This is the only option needed
         for initiator. -->
    <ike-redirect/>

  </params>
  <policy>

    <tunnel name="host-to-host" flags="auto">
      <identity id-type="email" id="a@ipsec.com">
        <local-secret>foo</local-secret>
      </identity>
      <!-- IP address of gateway -->
      <peer>172.30.4.10</peer>
    </tunnel>

    <rule to-tunnel="host-to-host">
    </rule>

    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>
  </policy>
</quicksec>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hostb-ikev1-main-mode.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Peer-to-peer setup using IKEv1 main mode. -->
<!-- Related: hosta-ikev1-main-mode.xml -->
<quicksec>
  <policy>

    <tunnel name="host-to-host" flags="auto">
      <!-- local identity sent to the remote IKE peer -->
      <identity id-type="email" id="b@ipsec.com">
        <!-- shared secret used between the IKEv1 peers -->
        <local-secret>foo</local-secret>
      </identity>
      <!-- Enable the use of IKEv1 protocol -->
      <ike-versions>1</ike-versions>
    </tunnel>

    <!-- Allows src address to initiate traffic to the dst address,
         packet matching to these selectors triggers IKE negotiation.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule to-tunnel="host-to-host">
      <src>ipv4(172.30.4.167)</src>
      <dst>ipv4(172.30.4.189)</dst>
    </rule>

    <!-- Allows src address to initiate traffic to the dst address, 
         if the packet came from the specified from-tunnel.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule from-tunnel="host-to-host">
      <src>ipv4(172.30.4.189)</src>
      <dst>ipv4(172.30.4.167)</dst>
    </rule>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>
  </policy>
</quicksec>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hosta-cp-iras-mobike.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Remote access gateway setup. Client instance with cfgmode and -->
<!-- virtual adapter support is required on the client side. -->
<quicksec>
  <params>
    <!-- return routability policy for responder: 
         before-sa-update (default), after-sa-update, no-rrc -->
    <mobike rrc-policy="before-sa-update"/>

    <!-- IRAS gives virtual IP address from range defined 
         in address element. Subnet element defines which subnet
         is accessible through the gateway. More than one subnet
         element can be defined. -->
    <address-pool>
      <subnet>192.168.200.0/24</subnet>
      <subnet>192.168.100.0/24</subnet>
      <address netmask="255.255.255.0">192.168.200.3-192.168.200.254</address>
    </address-pool> 

    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- shared secret and identity of remote IKE peer -->
      <remote-secret id-type="email" 
                     id="b@ipsec.com">foo</remote-secret>
    </auth-domain>
  </params>
  <policy>

    <!-- The flag mobike enables mobike suports for IKE SAs negotiated
         using this tunnel. The flag allow-cfgmode allows initiators to
         request remote access attributes using IKEv2 configuration 
         payloads. --> 
    <tunnel name="remote-access" flags="mobike
                                        allow-cfgmode">
      <!-- local identity sent to the remote IKE peer -->
      <identity id-type="email" id="a@ipsec.com">
        <!-- local shared secret -->
        <local-secret>foo</local-secret>
      </identity>
      <!-- Precedence is used on responder when selecting a new 
           local IP address, if the current address has disappeared. -->
      <local-ip precedence="0xffffffff">172.30.4.189</local-ip>
      <!-- IPv4 and IPv6 (except link-local) addresses from local 
           interface are added to the local IP address list with 
           the specified precedence. -->
      <local-interface precedence="1">eth1</local-interface>
    </tunnel>

    <!-- Allow traffic from the remote access clients. -->
    <rule from-tunnel="remote-access"/>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>
  </policy>
</quicksec>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hosta-cp-iras-dhcp-addrpool.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">

<!-- Remote access gateway setup. Client instance with cfgmode and -->
<!-- virtual adapter support is required on the client side. -->
<quicksec>
  <params>
    <!-- IRAS simply distributes the DHCP addresses (received from
	 the DHCP server) to the client. -->
    <address-pool name="pool1"
                  dhcp="192.168.1.254,67"
	          own-ip="192.168.1.100,68,67"
		  flags="dhcp-ras"/>

    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- shared secrets and identities of remote IKE peers -->
      <remote-secret id-type="email"
                     id="b@ipsec.com">foo</remote-secret>
      <remote-secret id-type="email"
                     id="c@ipsec.com">foobar</remote-secret>
    </auth-domain>
  </params>
  <policy>

    <tunnel name="remote-access" flags="require-cfgmode
                                        allow-cfgmode">
      <!-- local identity sent to the remote IKE peer.
           local shared secret is taken from the remote secret
           based on the remote identity, if local-secret has
           not been specified as in this example. -->
      <tunnel-address-pool name="pool1"/>
      <identity id-type="email" id="a@ipsec.com"/>
      <ike-versions>2</ike-versions>
    </tunnel>

    <!-- Allow traffic from the remote access clients. -->
    <rule from-tunnel="remote-access"/>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>

  </policy>
</quicksec>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hostb-xauth-client.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Remote access setup using xauth. -->
<!-- Related: hosta-xauth-gw.xml -->
<quicksec>
  <params>
    <!-- Authentication credentials for XAuth. -->
    <!--      <client-auth type="xauth" user-name="user1" password="password"/> -->
    <client-auth type="xauth" user-name="luser" password="luser"/>
  </params>
  <policy>

    <!-- xauth-methods flag set the authentication method
         so that the client informs the remote peer
         that Xauth would be desirable. If the remote
         peer does not start Xauth within 5 seconds the
         client continues with QuickMode negotiation. 
         Without this flag the QuickMode is started
         immediately after the IKE negotiation completes,
         but the remote peer can still start Xauth
         authentication. -->
    <tunnel name="host-to-host" flags="xauth-methods auto">
      <!-- local identity sent to the remote IKE peer -->
      <identity id-type="email" id="b@ipsec.com">
        <!-- local shared secret -->
        <local-secret>foo</local-secret>
      </identity>
      <ike-versions>1</ike-versions>
    </tunnel>

    <!-- Allows src address to initiate traffic to the dst address,
         packet matching to these selectors triggers IKE negotiation.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule to-tunnel="host-to-host">
      <src>ipv4(172.30.4.167)</src>
      <dst>ipv4(172.30.4.189)</dst>
    </rule>

    <!-- Allows src address to initiate traffic to the dst address, 
         if the packet came from the specified from-tunnel.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule from-tunnel="host-to-host">
      <src>ipv4(172.30.4.189)</src>
      <dst>ipv4(172.30.4.167)</dst>
    </rule>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>
  </policy>
</quicksec>
