=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/apps/quicksec.dtd
<!--                                                                    -->
<!-- quicksec.dtd                                                       -->
<!--                                                                    -->
<!-- @copyright                                                         -->
<!-- Copyright (c) 2002 - 2016, INSIDE Secure Oy.  All rights reserved. -->
<!--                                                                    -->
<!-- Document type description for QuickSec XML policy files.           -->
<!--                                                                    -->
<!--                                                                    -->

<!-- Built-in entities:                                                 -->
<!--                                                                    -->
<!--   quicksec:hostname                                                -->
<!--   quicksec:version                                                 -->
<!--   quicksec:ifname(IFINDEX[,TYPE])                                  -->
<!--     where:                                                         -->
<!--       IFINDEX  is the interface number                             -->
<!--       TYPE     is `any', `loopback' or `physical'                  -->
<!--                                                                    -->


<!-- Tunable parameters used in the policy. -->

<!ENTITY vpn-a-transform    'esp 3des sha1'>

<!ENTITY vpn-a-group        '2'>

<!ENTITY vpn-a-ike-life     '86400'>

<!ENTITY vpn-a-ipsec-life   '28800'>

<!ENTITY vpn-b-transform    'esp aes xcbc-aes'>

<!ENTITY vpn-b-group        '14'>

<!ENTITY vpn-b-ike-life     '86400'>

<!ENTITY vpn-b-ipsec-life   '28800'>

<!-- Default lifetime type. -->
<!ENTITY % default-life-type    '"kbytes"'>

<!-- Default rule type. -->
<!ENTITY % default-rule-type    '"pass"'>

<!-- Policy elements and their attributes. -->

<!-- The top-level element. -->
<!ELEMENT quicksec  (params?,policy+)>

<!-- Parameter element. -->
<!ELEMENT params (audit?
                  ,http-interface?
                  ,dns?
                  ,xauth-tester?
                  ,mobike?
                  ,(address-pool
                    |externalkey
                    |ldap
                    |client-auth
                    |group
                    |auth-domain)*
                  ,xauth-method?
                  ,radius-accounting?
                  ,ike-redirect?
                  ,ike-fragmentation?)>

<!-- IKEv2 Fragmentation -->
<!ELEMENT ike-fragmentation     EMPTY>
<!ATTLIST ike-fragmentation
          status                (disabled|enabled)  "enabled"
          fragment-size         CDATA               "1280">

<!-- IKE Redirect -->
<!--  phase: ike-init -->
<!ELEMENT ike-redirect (redirect-address*)>
<!ATTLIST ike-redirect
          phase     CDATA    #IMPLIED>


<!-- cookie-required : with ikev2 always do cookie exchange -->
<!-- certificate-provider : enable hash-and-url certificate provider -->
<!-- certificate-bundles : send hash-and-url certificates as bundles -->
<!ATTLIST params
          flags                         NMTOKENS    #IMPLIED
          debug                         CDATA       #IMPLIED
          certificate-provider-port     CDATA       "7369">

<!-- Audit Configuration. -->
<!ELEMENT audit (module*)>
<!ATTLIST audit
          snap-length   CDATA     "0">

<!ELEMENT module    EMPTY>
<!ATTLIST module
          log-to    CDATA         "syslog"
          format    NMTOKENS      "default">
<!-- all ike pm -->
<!ATTLIST module
          subsystem     NMTOKENS      "all">

<!-- HTTP statistics interface. -->
<!ELEMENT http-interface    EMPTY>
<!ATTLIST http-interface
          address       CDATA       #IMPLIED
          port          CDATA       "7368"
          frames        (yes|no)    "no"
          refresh       CDATA       "0">

<!-- DNS name resolver utilization. -->
<!ELEMENT dns                   EMPTY>

<!-- XAUTH tester. -->
<!ELEMENT xauth-tester  ANY>

<!-- Mobike. rrc-policy: before-sa-update after-sa-update no-rrc -->
<!ELEMENT mobike                EMPTY>
<!ATTLIST mobike
          rrc-policy            CDATA           #IMPLIED>

<!-- Address pool for allocating IP addresses for remote access -->
<!-- clients. -->
<!ELEMENT address-pool  (subnet*,address*,ipv6-prefix?)>
<!ATTLIST address-pool
          name      ID      #IMPLIED
          own-ip    CDATA   #IMPLIED
          dns       CDATA   #IMPLIED
          wins      CDATA   #IMPLIED
          dhcp      CDATA   #IMPLIED
          flags     CDATA   #IMPLIED>

<!-- Additional sub-networks, protected by the gateway -->
<!-- (SUBNET/MASKLEN). -->
<!ELEMENT subnet    (#PCDATA)>

<!-- IPv6 prefix, used when clients specify the low-order address bits -->
<!ELEMENT ipv6-prefix   (#PCDATA)>

<!-- An IP address specification.  Possible formats are:        -->
<!--   IPADDR       a single IP address                 -->
<!--   IPADDR-IPADDR    an IP address range                 -->
<!--   IPADDR/MASKLEN   all addresses of the subnet.  If the netmask    -->
<!--            attribute is unspecified, use the netmask   -->
<!--            MASKLEN.                    -->
<!ELEMENT address   (#PCDATA)>
<!ATTLIST address
          netmask   CDATA   #IMPLIED>

<!-- Externalkey provider. -->
<!ELEMENT externalkey   EMPTY>
<!ATTLIST externalkey
      type      CDATA       #REQUIRED
      init-info CDATA       #IMPLIED>

<!-- trust-cas -->
<!ATTLIST externalkey
      flags     NMTOKENS    #IMPLIED>

<!-- An LDAP server. -->
<!ELEMENT ldap EMPTY>
<!ATTLIST ldap
      server    CDATA   #REQUIRED
      port      CDATA   "389">

<!-- Remote access client authentication. -->
<!ELEMENT client-auth   EMPTY>
<!ATTLIST client-auth
          type      (xauth|eap)            #IMPLIED
          gateway   CDATA                   #IMPLIED
          order         (1|2)                       #IMPLIED
          user-name CDATA                   #REQUIRED
          password  CDATA                   #REQUIRED>

<!-- Authentication domains -->
<!ELEMENT auth-domain ((remote-secret
                       |certificate
                       |ca
                       |crl
                       |eap
                       |radius-client|radius
                       |password)*)>
<!ATTLIST auth-domain
          name          CDATA    #IMPLIED>

<!-- User-name - password based authentication at the remote access -->
<!-- gateway. -->
<!ELEMENT password  EMPTY>
<!ATTLIST password
          user-name             CDATA               #REQUIRED
          password              CDATA               #REQUIRED
          user-name-encoding    (binary|hex)        "binary"
          password-encoding     (binary|hex)        "binary">

<!-- Additional manually configured certificates and CRLs. -->

<!ELEMENT certificate   (#PCDATA)>
<!ATTLIST certificate
          file      CDATA   #IMPLIED>

<!ELEMENT crl       (#PCDATA)>
<!ATTLIST crl
          file      CDATA   #IMPLIED>

<!-- A pre-shared key for a remote IKE peer. -->
<!ELEMENT remote-secret     (#PCDATA)>
<!ATTLIST remote-secret
          id-type     (dn|ip|fqdn|email|key-id|idlist)    #IMPLIED
          id          CDATA                               #IMPLIED
          id-encoding (binary|hex)                        "binary"
          encoding    (binary|hex)                        "binary">

<!-- EAP configuration -->
<!ELEMENT eap           EMPTY>
<!ATTLIST eap
          type          (md5-challenge
                         |sim
                         |aka
                         |srp
                         |tls
                         |aka-dash
                         |mschapv2)                             #IMPLIED
          radius-url    CDATA                                   #IMPLIED
          preference    CDATA                                   #IMPLIED>


<!-- RADIUS client information. -->
<!ELEMENT radius-client     EMPTY>
<!ATTLIST radius-client
          address               CDATA   #REQUIRED
          port                  CDATA   #IMPLIED
          nas-ip-address        CDATA   #IMPLIED
          nas-identifier        CDATA   #IMPLIED
          max-retransmit-timer  CDATA   #IMPLIED
          max-retransmissions   CDATA   #IMPLIED>

<!-- RADIUS server information. -->
<!ELEMENT radius    EMPTY>
<!ATTLIST radius
          server    CDATA   #REQUIRED
          port      CDATA   "1812"
          acct-port CDATA   "1813"
          secret    CDATA   #REQUIRED>

<!-- Access control group. -->
<!ELEMENT group (constraint+)>
<!ATTLIST group
          name  CDATA   #REQUIRED>

<!-- Constraint for members of an access control group. -->
<!ELEMENT constraint    EMPTY>
<!ATTLIST constraint
          type      (xauth
                     |eap
                     |key-subject
                     |eap-subject
                     |cert-subject
                     |cert-issuer
                     |ca-subject)           #REQUIRED>
<!-- Type           Field   Pattern             -->
<!-- ================================================================== -->
<!-- xauth          radius  AVP=PATTERN         -->
<!-- For `{cert,ca}-subject'    dn  PATTERN for subjectName     -->
<!-- and `cert-issuer'      ip  PATTERN for IP subjectAltName   -->
<!-- types          fqdn    PATTERN for fqdn subjectAltName -->
<!--                email   PATTERN for emailsubjectAltName -->
<!-- key-subject may use ip, fqdn, email and key-id types -->


<!-- eap   auth-method  PATTERN sim|aka|tls|md5-challenge|aka-dash      -->
<!-- eap-subject Field may be ip, fqdn, email or key-id                 -->
<!-- eap-subject Pattern  should match the EAP identity                 -->

<!ATTLIST constraint
          field     CDATA               #IMPLIED
          pattern   CDATA               #IMPLIED>


<!-- Type of External authentication method used for authentication. -->
<!-- The method type and flag values should have the following values-->
<!--  Type                              FLAG                         -->
<!-- =============================================================== -->
<!-- generic                           simple                        -->
<!--                                   securid                       -->
<!-- radius-chap                                                     -->
<!-- otp                                                             -->
<!-- s-key                                                           -->
<!ELEMENT xauth-method EMPTY>
<!ATTLIST xauth-method
          type     CDATA #IMPLIED
          flag     CDATA #IMPLIED>


<!ELEMENT radius-accounting (radius-client, radius+)>
<!ATTLIST radius-accounting>

<!-- Policy element. -->
<!ELEMENT policy ((ldap
                   |password
                   |ike-defaults
                   |certificate
                   |crl
                   |group)*
                  ,(tunnel|rule)+)>
<!ATTLIST policy
          id            ID      #IMPLIED
          precedence    CDATA   #IMPLIED
          size          CDATA   #IMPLIED
          refresh       CDATA   "0">

<!-- Default IKE parameters and algorithms. -->
<!ELEMENT ike-defaults  EMPTY>
<!-- cipher1 cipher2 null des 3des aes aes-ctr aes-gcm aes-gcm-64 -->
<!-- aes-gcm-96 aes-ccm aes-ccm-64 aes-ccm-96 -->
<!-- mac1 mac2 md5 sha1 -->
<!ATTLIST ike-defaults
          algorithms    NMTOKENS    #IMPLIED>

<!-- A tunnel specification. -->
<!ELEMENT tunnel    ((ike-versions
             |ike-groups
             |pfs-groups
             |life
             |certificate
             |identity
             |authentication
             |dpd-timeout
             |ike-algorithms
             |ike-window-size
             |local-ip
             |local-interface
             |local-port
             |ipsec-idle-timeout
             |peer
             |algorithm-properties
             |tunnel-address-pool
             |redirect-address
             |ike-fragmentation)*)>

<!ATTLIST tunnel
          name              ID      #REQUIRED
          app-id            CDATA   #IMPLIED
          ike-life          CDATA   #IMPLIED
          routing-instance  CDATA   #IMPLIED>

<!-- cipher1 cipher2 null des 3des aes aes-ctr aes-gcm aes-gcm-64 -->
<!-- aes-gcm-96 aes-ccm aes-ccm-64 aes-ccm-96 -->
<!-- mac1 mac2 md5 sha1 sha2 xcbc-aes gmac-aes -->
<!-- esp -->
<!-- Default transform is "esp aes 3des sha1 md5" -->

<!ATTLIST tunnel
          transform NMTOKENS    #IMPLIED>

<!-- perhost perport dont-initiate dhcp -->
<!-- omit-trigger-packet aggressive-mode allow-dhcp -->
<!-- allow-cfgmode require-cfgmode auto -->
<!-- tunnel transport disable-anti-replay eap-request-id -->
<!-- eap-only-authentication start-with-natt dont-initiate-natt -->
<!-- disable-natt no-nats-allowed xauth-methods mobike -->
<!-- long-seq short-seq no-cert-chains -->
<!ATTLIST tunnel
          flags     NMTOKENS    #IMPLIED>

<!ELEMENT redirect-address  (#PCDATA)>

<!-- An IKE peer, IP address or Domain name -->
<!ELEMENT peer  (#PCDATA)>

<!-- Local IP address to be used with a tunnel. -->
<!ELEMENT local-ip  (#PCDATA)>
<!ATTLIST local-ip
          precedence    NMTOKENS    #IMPLIED>

<!-- Local interface to be used with a tunnel. -->
<!ELEMENT local-interface (#PCDATA)>
<!ATTLIST local-interface
          precedence    NMTOKENS    #IMPLIED>

<!-- Local IKE port to be used with the tunnel. -->
<!ELEMENT local-port    (#PCDATA)>

<!-- DPD timeout. -->
<!ELEMENT dpd-timeout    (#PCDATA)>

<!-- Allowed Diffie-Hellman groups for IKE. -->
<!ELEMENT ike-groups    (#PCDATA)>
<!-- system-preferences -->
<!ATTLIST ike-groups
          flags     NMTOKENS    #IMPLIED>

<!-- Allowed IKE versions, currently support 1 and 2.   -->
<!-- If both given, initiator starts with version 2.    -->
<!-- If only 2 given start with version 2, no fallback. -->
<!-- If only 1 given, start with version 1, and on responder set USE_V1. -->
<!ELEMENT ike-versions (#PCDATA)>

<!-- Idle timeout be used with the tunnel. -->
<!ELEMENT ipsec-idle-timeout    (#PCDATA)>

<!-- Perfect forward secrecy. -->
<!ELEMENT pfs-groups    (#PCDATA)>
<!-- system-preferences -->
<!ATTLIST pfs-groups
          flags     NMTOKENS    #IMPLIED>

<!-- A required access control group. -->
<!ELEMENT access-group  (#PCDATA)>

<!-- SA lifetime. -->
<!ELEMENT life  (#PCDATA)>
<!ATTLIST life
          type  (kbytes|seconds)    %default-life-type;>

<!-- Trusted CA. -->
<!ELEMENT ca    (#PCDATA)>
<!ATTLIST ca
          file  CDATA       #IMPLIED>
<!-- no-crl -->
<!ATTLIST ca
          flags NMTOKENS    #IMPLIED>

<!-- An IKE identity. -->
<!ELEMENT identity (local-secret*)>

<!-- A pre-shared key for tunnel authenticaton. -->
<!ELEMENT local-secret                        (#PCDATA)>
<!ATTLIST local-secret
          encoding      (binary|hex)           "binary"
          flags         NMTOKENS               #IMPLIED>


<!ATTLIST identity
          id-type      (dn|ip|fqdn|email|key-id|idlist)    #IMPLIED
          id           CDATA                               #IMPLIED
          id-encoding  (binary|hex)                        "binary"
          type         (local|remote)                      "local"
          order        (1|2)                               "1">

<!-- enforce-identity -->
<!ATTLIST identity
          flags NMTOKENS    #IMPLIED>

<!-- Tunnel authentication -->
<!ELEMENT authentication    EMPTY>
<!ATTLIST authentication
          auth-domain-name      CDATA           #IMPLIED
          order                 (1|2)           "1">

<!-- Algorithm properties. -->
<!ELEMENT algorithm-properties  EMPTY>
<!-- cipher1 cipher2 aes aes-ctr aes-gcm aes-gcm-64 aes-gcm-96 gmac-aes -->
<!-- aes-ccm aes-ccm-64 aes-ccm-96 sha2 mac1 mac2 -->

<!ATTLIST algorithm-properties
          algorithm     NMTOKENS    #REQUIRED>

<!ATTLIST algorithm-properties
          min-key-size      CDATA           #REQUIRED
          max-key-size      CDATA           #REQUIRED
          default-key-size  CDATA           #REQUIRED
          scope             (ike|ipsec|all) "all">

<!-- Algorithms for IKE SAs. -->
<!-- cipher1 cipher2 des 3des aes aes-ctr mac1 mac2 md5 sha1 sha2 xcbc-aes -->
<!-- aes-gcm aes-gcm-64 aes-gcm-96 aes-ccm aes-ccm-64 aes-ccm-96 -->
<!ELEMENT ike-algorithms    (#PCDATA)>

<!ELEMENT ike-window-size   (#PCDATA)>

<!-- Configuring address pools to tunnels -->
<!ELEMENT tunnel-address-pool  EMPTY>
<!ATTLIST tunnel-address-pool
          name          IDREF                   #REQUIRED>

<!-- A policy rule. -->
<!ELEMENT rule     ((src|src-dns)?
                   ,(dst|dst-dns)?
                   ,access-group*)>

<!ATTLIST rule
          app-id                    ID                  #IMPLIED
          precedence                CDATA               #IMPLIED
          type                      (pass|reject|drop)  %default-rule-type;
          from-tunnel               IDREF               #IMPLIED
          to-tunnel                 IDREF               #IMPLIED
          routing-instance          CDATA               #IMPLIED>

<!-- connections -->
<!ATTLIST rule
          log       NMTOKENS        #IMPLIED>

<!-- rate-limit -->
<!ATTLIST rule
          flags     NMTOKENS        #IMPLIED>

<!-- Rule selectors. -->

<!ELEMENT src       (#PCDATA)>
<!ELEMENT dst       (#PCDATA)>
<!ELEMENT src-dns   (#PCDATA)>
<!ELEMENT dst-dns   (#PCDATA)>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hostb-eap-client.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Client-server setup using EAP. -->
<!-- Related: hosta-eap-gw.xml -->
<quicksec>
  <!-- to generate the CA and end entity certificates used in this
       sample, please execute 'ssh-certmake cert_template.rsa'
       (found from the src/quicksec/samples directory).
       This will generate the necessary files needed by this policy.
       This operation must be done only on one of the test hosts!
       Copy the generated rsa* files to local and to remote IKE
       peer's directory (where policy manager is located). -->
  <params>
    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- Trusted CA -->
      <ca file="rsaca.ca"/>

      <!-- static CRL from a file-->
      <crl file="rsaca.crl"/>

      <!-- EAP type -->
      <eap type="md5-challenge"/>
      <!-- <eap type="sim"/> -->
      <!-- <eap type="tls"/> -->
      <!-- <eap type="aka"/> -->
      <!-- <eap type="mschapv2"/> -->
    </auth-domain>

    <!-- username and password for EAP authentication.
         Note that the username is identical to the local identity in
         the tunnel "host-to-host" below. In IKEv2, the EAP server should 
         not send EAP identity requests to the client when performing EAP 
         authentication as the client has already sent its identity in the 
         first IKE_AUTH message. The identity the client will use in 
         IKE_AUTH message is the tunnel's local identity. If the EAP server
         does send an EAP identity request, the client will respond to the EAP 
         identity request with the username as configured in the client-auth 
         block below. In any case, the password is used for md5-challenge
         authentication.
         EAP-SIM and EAP-AKA do not use the password at all because
         authentication secrets are stored in a SIM/USIM card. If the server
         sends an EAP identity request, the username configured here is used
         by EAP-SIM or EAP-AKA as follows: if the username is complete, e.g.
         "user@domain" then that username is used unchanged. If it contains
         a domain only, e.g. "@domain" then the IMSI is obtained from the
         SIM/USIM card, prefixed with "1" (EAP-SIM) or "0" (EAP-AKA) and the
         domain part is appended to it to form the final username, for example
         "0555444333222111@domain". If no username is configured here then
         the prefixed IMSI is used without any domain part. -->
    <client-auth type="eap" user-name="user@domain" password="password"/> 
  </params>
  <policy>

    <tunnel name="host-to-host" flags="auto">
      <!-- local identity sent to the remote IKE peer 
           local identity must be the same as the user-name in the 
           client-auth element -->
      <identity id-type="email" id="user@domain"/>
    </tunnel>

    <rule to-tunnel="host-to-host">
      <src>ipv4(172.30.4.167)</src>
      <dst>ipv4(172.30.4.189)</dst>
    </rule>

    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>
  </policy>
</quicksec>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hostb-ipv6.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Peer-to-peer setup with IKEv6. -->
<!-- Related: hosta-ipv6.xml -->
<quicksec>
  <params>
    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- shared secret and identity of remote IKE peer -->
      <remote-secret id-type="email" 
                     id="a@ipsec.com">foo</remote-secret>
    </auth-domain>
  </params>
  <policy>

    <tunnel name="host-to-host" flags="auto">
      <!-- local identity sent to the remote IKE peer -->
      <identity id-type="email" id="b@ipsec.com">
        <!-- local shared secret -->
        <local-secret>foo</local-secret>
      </identity>
    </tunnel>

    <!-- Allows src address to initiate traffic to the dst address,
         packet matching to these selectors triggers IKE negotiation.
         Protocol/port information can be encoded in the traffic
         selector as ipv6(protocol:port,a:b:c:d:e:f:g:h) -->
    <rule to-tunnel="host-to-host">
      <src>ipv6(5001::2)</src>
      <dst>ipv6(5001::1)</dst>
    </rule>

    <!-- Allows src address to initiate traffic to the dst address, 
         if the packet came from the specified from-tunnel.
         Protocol/port information can be encoded in the traffic
         selector as ipv6(protocol:port,a:b:c:d:e:f:g:h) -->
    <rule from-tunnel="host-to-host">
      <src>ipv6(5001::1)</src>
      <dst>ipv6(5001::2)</dst>
    </rule>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv6(::/0)</src>
      <dst>ipv6(::/0)</dst>
    </rule>
  </policy>
</quicksec>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hosta-certificate-ecdsa.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Peer-to-peer setup with ecdsa certificates. -->
<!-- Related: hostb-certificate-ecdsa.xml -->
<quicksec>
  <!-- to generate the CA and end entity certificates used in this
       sample, please execute 'ssh-certmake cert_template.ecdsa'
       (found from the src/quicksec/samples directory).
       This will generate the necessary files needed by this policy.
       This operation must be done only on one of the test hosts!
       Copy the generated ecdsa* files to local and to remote IKE
       peer's directory (where policy manager is located). -->
  <params>
    <!-- local certificate and private key -->
    <externalkey type="software" init-info="key_files(ecdsauser1.crt, 
                                            ecdsauser1.prv)"/>
    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- Trusted CA -->
      <ca file="ecdsaca.ca"/>

      <!-- static CRL from a file-->
      <crl file="ecdsaca.crl"/>
    </auth-domain>
  </params>
  <policy>

    <tunnel name="host-to-host">
      <!-- local identity sent to the remote IKE peer -->
      <identity id-type="email" id="ecdsauser1@ipsec.com"/>
    </tunnel>

    <!-- Allows src address to initiate traffic to the dst address,
         packet matching to these selectors triggers IKE negotiation.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule to-tunnel="host-to-host">
      <src>ipv4(172.30.4.189)</src>
      <dst>ipv4(172.30.4.167)</dst>
    </rule>

    <!-- Allows src address to initiate traffic to the dst address, 
         if the packet came from the specified from-tunnel.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule from-tunnel="host-to-host">
      <src>ipv4(172.30.4.167)</src>
      <dst>ipv4(172.30.4.189)</dst>
    </rule>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>

  </policy>
</quicksec>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hostb-sha512.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Peer-to-peer setup with SHA2 512. -->
<!-- Related: hosta-sha512.xml -->
<quicksec>
  <params>
    <http-interface/>
    <auth-domain>
      <!-- shared secret and identity of remote IKE peer -->
      <remote-secret id-type="email" 
                     id="a@ipsec.com">foo</remote-secret>
    </auth-domain>
  </params>
  <policy>

    <tunnel name="host-to-host" transform="aes sha2 esp" flags="auto">
      <!-- local identity sent to the remote IKE peer -->
      <identity id-type="email" id="b@ipsec.com">
        <!-- local shared secret -->
        <local-secret>foo</local-secret>
      </identity>
      <ike-algorithms>aes sha2</ike-algorithms>
      <algorithm-properties algorithm="aes" 
                            min-key-size="256" max-key-size="256" 
                            default-key-size="256"/>
      <algorithm-properties algorithm="sha2" 
                            min-key-size="512" max-key-size="512" 
                            default-key-size="512"/>
    </tunnel>

    <!-- Allows src address to initiate traffic to the dst address,
         packet matching to these selectors triggers IKE negotiation.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule to-tunnel="host-to-host">
      <src>ipv4(172.30.4.167)</src>
      <dst>ipv4(172.30.4.189)</dst>
    </rule>

    <!-- Allows src address to initiate traffic to the dst address, 
         if the packet came from the specified from-tunnel.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule from-tunnel="host-to-host">
      <src>ipv4(172.30.4.189)</src>
      <dst>ipv4(172.30.4.167)</dst>
    </rule>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>
  </policy>
</quicksec>

=== stkuroneko/asuswrt-modx-next/release/src/router/quicksec-7.0/src/quicksec/samples/hostb-pfs-groups.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quicksec PUBLIC "quicksec:dtd" "quicksec.dtd">


<!-- Peer-to-peer setup defining PFS groups. -->
<!-- Related: hosta-pfs-groups.xml -->
<quicksec>
  <params>
    <!-- Authentication domain specifies IKE authentication
         parameters -->
    <auth-domain>
      <!-- shared secret and identity of remote IKE peer -->
      <remote-secret id-type="email"
                     id="a@ipsec.com">foo</remote-secret>
    </auth-domain>
  </params>
  <policy>

    <tunnel name="host-to-host" flags="auto">
      <!-- local identity sent to the remote IKE peer -->
      <identity id-type="email" id="b@ipsec.com">
        <!-- local shared secret -->
        <local-secret>foo</local-secret>
      </identity>
      <!-- allowed MODP groups for IPSec SA negotiation.
           The PFS operation is not performed for initial
           IPSec SA.
           Supported values are 1, 2, 5 and 14 through 26. -->
      <pfs-groups>14 15</pfs-groups>
      <!-- Set the lifetime for IPSec SA to be 5 minutes
           (300 seconds). The default lifetime for IPSec
           SA is 8 hours (28800 seconds). -->
      <life type="seconds">300</life>
    </tunnel>

    <!-- Allows src address to initiate traffic to the dst address,
         packet matching to these selectors triggers IKE negotiation.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule to-tunnel="host-to-host">
      <src>ipv4(172.30.4.167)</src>
      <dst>ipv4(172.30.4.189)</dst>
    </rule>

    <!-- Allows src address to initiate traffic to the dst address,
         if the packet came from the specified from-tunnel.
         Protocol/port information can be encoded in the traffic
         selector as ipv4(protocol:port,a.b.c.d) -->
    <rule from-tunnel="host-to-host">
      <src>ipv4(172.30.4.189)</src>
      <dst>ipv4(172.30.4.167)</dst>
    </rule>

    <!-- Pass rule, that handles all traffic not matching
         to traffic selectors on any higher precedence rules.
         Remove this rule if plain text traffic is forbidden. -->
    <rule>
      <src>ipv4(0.0.0.0/0)</src>
      <dst>ipv4(0.0.0.0/0)</dst>
    </rule>
  </policy>
</quicksec>
